services:
  stats-server:
    build: ./stats/stats-service
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - spring.datasource.url=jdbc:postgresql://stats-db:5432/ewm-stats
      - spring.datasource.username=postgres
      - spring.datasource.password=12345
      - server.port=9090

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345

  ewm-service:
    build: ./ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - spring.datasource.url=jdbc:postgresql://ewm-db:5432/ewm-main
      - spring.datasource.username=postgres
      - spring.datasource.password=12345

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
